# -*- coding: utf-8 -*-
"""Proyecto final final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fq1jMhBbvsOeNSD5nfUHX8TRjr98jkee
"""

import pandas as pd

df = pd.read_csv('/content/chicago crimes.csv')
display(df.head())

"""## Data Cleaning and Preprocessing"""

print('DataFrame Info:')
df.info()

print('Missing values per column:')
print(df.isnull().sum())

initial_rows = df.shape[0]
df.drop_duplicates(inplace=True)
print(f'Removed {initial_rows - df.shape[0]} duplicate rows.')
print(f'DataFrame now has {df.shape[0]} rows.')

# Convert 'Date' to datetime objects
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Convert ID and Case Number to string
df['ID'] = df['ID'].astype(str)
df['Case Number'] = df['Case Number'].astype(str)

# Convert Arrest and Domestic to boolean
df['Arrest'] = df['Arrest'].astype(bool)
df['Domestic'] = df['Domestic'].astype(bool)

# Convert coordinate columns to numeric, coercing errors to NaN
df['X Coordinate'] = pd.to_numeric(df['X Coordinate'], errors='coerce')
df['Y Coordinate'] = pd.to_numeric(df['Y Coordinate'], errors='coerce')
df['Latitude'] = pd.to_numeric(df['Latitude'], errors='coerce')
df['Longitude'] = pd.to_numeric(df['Longitude'], errors='coerce')

# Ensure 'Location Description' is string type to handle mixed types warning
df['Location Description'] = df['Location Description'].astype(str)

print('\nData types after conversion:')
df.info()

# Re-check missing values after type coercion
print('Missing values before imputation:')
print(df.isnull().sum()[df.isnull().sum() > 0])

# Impute missing categorical values with 'UNKNOWN'
for col in ['Location Description', 'Ward', 'Community Area', 'District', 'FBI Code']:
    if col in df.columns:
        df[col] = df[col].fillna('UNKNOWN')

# For numerical coordinate columns, if still missing, we can fill with 0 or the median, or drop.
# Given they are coordinates, a simple fill with 0 might indicate an invalid location.
# For now, let's fill them with their median to retain as much data as possible while providing a plausible value.
# However, it's often better to drop rows with missing coordinates if location analysis is critical.
# For this task, I will fill with median as a general approach.
for col in ['X Coordinate', 'Y Coordinate', 'Latitude', 'Longitude']:
    if col in df.columns and df[col].isnull().any():
        median_val = df[col].median()
        df[col] = df[col].fillna(median_val)

# The 'Location' column is a string representation of coordinates. If 'Latitude' or 'Longitude' were missing,
# 'Location' might also be unparseable. Since we filled the numerical coordinates, we can try to reconstruct 'Location' if needed.
# For now, we will fill any remaining NaNs in 'Location' with 'UNKNOWN' as well.
if 'Location' in df.columns:
    df['Location'] = df['Location'].fillna('UNKNOWN')

# Drop rows where 'Date' is null, as it's a critical column for time-series analysis
df.dropna(subset=['Date'], inplace=True)

print('\nMissing values after imputation and dropping null dates:')
print(df.isnull().sum()[df.isnull().sum() > 0])

# Standardize 'Primary Type' and 'Description' to uppercase
df['Primary Type'] = df['Primary Type'].str.upper()
df['Description'] = df['Description'].str.upper()

print('\nUnique values for Primary Type (first 10 after standardization):')
print(df['Primary Type'].unique()[:10])

print('\nUnique values for Description (first 10 after standardization):')
print(df['Description'].unique()[:10])

# Display the first few rows of the cleaned DataFrame
print('\nCleaned DataFrame Head:')
display(df.head())

"""## Exploratory Data Analysis (EDA)"""

import matplotlib.pyplot as plt
import seaborn as sns

# Extract time-based features from the 'Date' column
df['Hour'] = df['Date'].dt.hour
df['Day_of_Week'] = df['Date'].dt.dayofweek # Monday=0, Sunday=6
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year

print("Added new time-based features: 'Hour', 'Day_of_Week', 'Month', 'Year'.")

plt.figure(figsize=(12, 7))
sns.countplot(y='Primary Type', data=df, order=df['Primary Type'].value_counts().index)
plt.title('Distribution of Primary Crime Types')
plt.xlabel('Number of Incidents')
plt.ylabel('Primary Type')
plt.show()

fig, axes = plt.subplots(2, 2, figsize=(18, 12))

sns.countplot(ax=axes[0, 0], x='Year', data=df)
axes[0, 0].set_title('Crime Incidents by Year')

sns.countplot(ax=axes[0, 1], x='Month', data=df)
axes[0, 1].set_title('Crime Incidents by Month')

sns.countplot(ax=axes[1, 0], x='Day_of_Week', data=df, order=range(7))
axes[1, 0].set_title('Crime Incidents by Day of Week')
axes[1, 0].set_xticklabels(['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'])

sns.countplot(ax=axes[1, 1], x='Hour', data=df)
axes[1, 1].set_title('Crime Incidents by Hour of Day')

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

sns.countplot(ax=axes[0], x='Arrest', data=df)
axes[0].set_title('Distribution of Arrests')

sns.countplot(ax=axes[1], x='Domestic', data=df)
axes[1].set_title('Distribution of Domestic Incidents')

plt.tight_layout()
plt.show()

arrest_rate_by_type = df.groupby('Primary Type')['Arrest'].mean().sort_values(ascending=False)

plt.figure(figsize=(12, 7))
sns.barplot(x=arrest_rate_by_type.values, y=arrest_rate_by_type.index)
plt.title('Arrest Rate by Primary Crime Type')
plt.xlabel('Arrest Rate')
plt.ylabel('Primary Type')
plt.show()

top_crime_types = df['Primary Type'].value_counts().nlargest(5).index

plt.figure(figsize=(15, 10))
for i, crime_type in enumerate(top_crime_types):
    plt.subplot(3, 2, i + 1)
    top_locations = df[df['Primary Type'] == crime_type]['Location Description'].value_counts().nlargest(5)
    sns.barplot(x=top_locations.values, y=top_locations.index)
    plt.title(f'Top 5 Locations for {crime_type}')
    plt.xlabel('Number of Incidents')
    plt.ylabel('Location Description')
plt.tight_layout()
plt.show()

crime_by_day_hour = df.groupby(['Day_of_Week', 'Hour']).size().unstack(fill_value=0)

plt.figure(figsize=(15, 8))
sns.heatmap(crime_by_day_hour, cmap='viridis', fmt='d')
plt.title('Crime Incidents by Day of Week and Hour')
plt.xlabel('Hour of Day')
plt.ylabel('Day of Week')
plt.yticks(ticks=range(7), labels=['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], rotation=0)
plt.show()

# Drop rows with NaN in Latitude/Longitude if any remained after imputation, or if UNKNOWN was filled in for location
df_geo = df.dropna(subset=['Latitude', 'Longitude'])

# Filter out potential 'UNKNOWN' locations that might have received median coordinates but are still not useful
df_geo = df_geo[df_geo['Location'] != 'UNKNOWN']

# Sample a subset for better visualization performance if the dataset is too large
if len(df_geo) > 100000:
    df_geo_sample = df_geo.sample(n=100000, random_state=42)
else:
    df_geo_sample = df_geo

plt.figure(figsize=(10, 10))
sns.kdeplot(x=df_geo_sample['Longitude'], y=df_geo_sample['Latitude'], fill=True, cmap='viridis') # Removed levels=100
plt.title('Geographical Crime Hotspots (KDE)')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.xlim([-87.9, -87.5]) # Approximate Chicago Longitude bounds
plt.ylim([41.6, 42.1]) # Approximate Chicago Latitude bounds
plt.gca().set_aspect('equal', adjustable='box')
plt.show()

"""## Feature Engineering and Data Transformation

To prepare the data for machine learning models, we need to transform features. This involves handling numerical scaling, creating new features from existing ones, and encoding categorical variables. We'll be mindful of memory by dropping highly redundant or very high-cardinality columns that might not add significant predictive power or are too memory-intensive to encode directly.
"""

from sklearn.preprocessing import StandardScaler
import numpy as np

print(f"Initial DataFrame size: {df.shape[0]} rows, {df.shape[1]} columns")

# Drop columns that are identifiers, redundant, or too granular
columns_to_drop = ['ID', 'Case Number', 'Block', 'Updated On', 'Location', 'IUCR', 'Description']
df_transformed = df.drop(columns=columns_to_drop, errors='ignore')

print(f"DataFrame size after dropping columns: {df_transformed.shape[0]} rows, {df_transformed.shape[1]} columns")

# Separate variables
y = df_transformed['Arrest']
X = df_transformed.drop(columns=['Arrest'])

print(f"X (features) shape: {X.shape}")
print(f"y (target) shape: {y.shape}")

# Identify numerical columns for scaling
coordinate_cols = ['X Coordinate', 'Y Coordinate', 'Latitude', 'Longitude']

# Identify numerical columns for scaling
coordinate_cols = ['X Coordinate', 'Y Coordinate', 'Latitude', 'Longitude']

# Initialize and fit the scaler (fit only on X to avoid data leakage)
scaler = StandardScaler()
X[coordinate_cols] = scaler.fit_transform(X[coordinate_cols])

print("Coordinate columns scaled successfully.")
display(X[coordinate_cols].head())

if 'Month' in X.columns and 'Day_of_Week' in X.columns and 'Hour' in X.columns:
    X['Month_sin'] = np.sin(2 * np.pi * X['Month'] / 12)
    X['Month_cos'] = np.cos(2 * np.pi * X['Month'] / 12)
    X['Day_of_Week_sin'] = np.sin(2 * np.pi * X['Day_of_Week'] / 7)
    X['Day_of_Week_cos'] = np.cos(2 * np.pi * X['Day_of_Week'] / 7)
    X['Hour_sin'] = np.sin(2 * np.pi * X['Hour'] / 24)
    X['Hour_cos'] = np.cos(2 * np.pi * X['Hour'] / 24)
    print("Cyclic features created.")
else:
    print("Skipping cyclic feature creation: original 'Month', 'Day_of_Week', or 'Hour' columns not found in X. They might have already been processed or dropped.")

# Drop original time columns after creating cyclic features
X = X.drop(columns=['Month', 'Day_of_Week', 'Hour', 'Date', 'Year'], errors='ignore')

columns_to_display = ['Month_sin', 'Month_cos', 'Day_of_Week_sin', 'Day_of_Week_cos', 'Hour_sin', 'Hour_cos']
existing_columns = [col for col in columns_to_display if col in X.columns]
if existing_columns:
    display(X[existing_columns].head())
else:
    print("Cyclic features are not present in X. Please ensure preceding cells to create them have been executed.")

if 'Primary Type' in X.columns:
    frequency_map_primary_type = X['Primary Type'].value_counts(normalize=True)
    X['Primary_Type_Frequency'] = X['Primary Type'].map(frequency_map_primary_type).fillna(0)
    X = X.drop(columns=['Primary Type'])
    print("Frequency encoded 'Primary Type'.")

# Frequency encode high cardinality categorical features
high_cardinality_cols = ['Location Description', 'District', 'Ward', 'Community Area', 'FBI Code']

high_cardinality_cols = ['Location Description', 'District', 'Ward', 'Community Area', 'FBI Code']
for col in high_cardinality_cols:
    if col in X.columns:
        # Ensure the column is treated as string for consistent frequency calculation
        X[col] = X[col].astype(str)
        # Calculate frequency
        frequency_map = X[col].value_counts(normalize=True)
        # Apply frequency encoding, handle categories not seen during mapping (though 'UNKNOWN' should catch most)
        X[col] = X[col].map(frequency_map).fillna(0) # Fillna(0) for any unseen values, though unlikely here.
        print(f"Frequency encoded '{col}'.")

print("Categorical features encoded.")
print(f"Final DataFrame shape: {X.shape}")
display(X.head())

"""## Dimensionality Reduction: PCA

### Why is Dimensionality Reduction Needed?

Our `X` DataFrame currently has 18 columns after feature engineering. While this isn't an extremely high number, it's a good practice to consider dimensionality reduction, especially with potentially correlated features like geographical coordinates and time-based cyclical features. The benefits include:

1.  **Reduced Computational Cost**: Fewer features mean faster training times for machine learning models.
2.  **Mitigation of the Curse of Dimensionality**: High-dimensional spaces can be sparse, making it harder for models to find patterns.
3.  **Improved Model Performance**: By removing noise and redundant features, models can sometimes generalize better.
4.  **Better Interpretability**: Although PCA components are less interpretable than original features, a reduced number of features can sometimes simplify analysis.

### PCA vs. LDA

*   **Principal Component Analysis (PCA)** is an **unsupervised** technique. It transforms the data into a new set of orthogonal (uncorrelated) variables called principal components. The first principal component accounts for the largest possible variance, and each succeeding component accounts for the highest possible variance under the constraint that it is orthogonal to the preceding components. PCA is suitable for our case because we want to reduce the feature space while retaining as much variance as possible, without explicitly using the target variable for the transformation.

*   **Linear Discriminant Analysis (LDA)** is a **supervised** technique used for classification. It finds linear combinations of features that best separate two or more classes. While we have a target variable (`Arrest`), LDA makes strong assumptions about the data (e.g., normal distribution of features within each class, equal covariance matrices across classes) which might not hold. Given that our primary goal is a general reduction of features for subsequent modeling, PCA is a more robust and commonly applied first step.
"""

from sklearn.decomposition import PCA
import seaborn as sns

# It's crucial to scale all numerical features before applying PCA.
# Identify all numerical columns in X that haven't been scaled yet.
# Boolean 'Domestic' can be treated as numerical (0 or 1).

# Create a working copy for PCA to avoid modifying the original X if not desired.
X_for_pca = X.copy()

# Ensure 'Domestic' is treated as numerical for scaling if it's still bool
if 'Domestic' in X_for_pca.columns and X_for_pca['Domestic'].dtype == 'bool':
    X_for_pca['Domestic'] = X_for_pca['Domestic'].astype(int)

numerical_cols_for_pca = X_for_pca.select_dtypes(include=np.number).columns.tolist()

# *** To prevent crashes on large datasets, we will sample the data for PCA analysis. ***
# A sample size of 100,000 is typically sufficient to get a representative scree plot.
sample_size = min(100000, len(X_for_pca))
print(f"Sampling {sample_size} rows for PCA analysis to manage memory...")
X_sampled_for_pca = X_for_pca.sample(n=sample_size, random_state=42)

print(f"Scaling {len(numerical_cols_for_pca)} numerical columns in the sampled data before PCA...")
scaler_pca = StandardScaler()
X_scaled_for_pca_sampled = scaler_pca.fit_transform(X_sampled_for_pca[numerical_cols_for_pca])

# Initialize PCA
# We will start by fitting PCA on all components to understand the explained variance.
# Later, we can select a specific number of components.
pca = PCA()
pca.fit(X_scaled_for_pca_sampled)

# Calculate cumulative explained variance
cum_explained_variance = np.cumsum(pca.explained_variance_ratio_)

# Plot the explained variance ratio
plt.figure(figsize=(10, 6))
plt.plot(range(1, len(cum_explained_variance) + 1), cum_explained_variance, marker='o', linestyle='--')
plt.title('Cumulative Explained Variance by Number of Principal Components (Scaled & Sampled Data)')
plt.xlabel('Number of Components')
plt.ylabel('Cumulative Explained Variance')
plt.grid(True)

# Add a horizontal line for 95% variance to help select components
plt.axhline(y=0.95, color='r', linestyle='-', label='95% Explained Variance')
plt.legend(loc='best')

plt.show()

# Print explained variance for each component and cumulative sum
print("Explained variance ratio for each component (on sampled data):")
for i, ratio in enumerate(pca.explained_variance_ratio_):
    print(f"PC {i+1}: {ratio:.4f}")

print("Cumulative explained variance (on sampled data):")
for i, cum_ratio in enumerate(cum_explained_variance):
    print(f"Up to PC {i+1}: {cum_ratio:.4f}")

"""### Investigating PCA Results: Why only one component?

The PCA results show that only the first principal component explains 100% of the variance, with all other components explaining 0%. This is highly unusual and suggests that there might be an issue with the input data `X`.

Possible reasons include:
1.  **Constant Features**: One or more features in `X` might have constant values (or nearly constant), providing no variance.
2.  **Perfect Multicollinearity**: Features might be perfectly correlated, meaning some features can be perfectly predicted from others, leading to a reduced effective dimensionality.
3.  **Numerical Stability Issues**: Very small or very large numbers in the features could lead to precision problems during PCA calculation.

Let's inspect the `X` DataFrame's descriptive statistics and the standard deviation of each column to understand this behavior.
"""

print('Overview of X DataFrame:')
X.info()

print('\nChecking for constant columns in X (where all values are identical):')
constant_cols = []
for col in X.columns:
    if X[col].nunique() == 1:
        constant_cols.append(col)

if len(constant_cols) > 0:
    print(f'\nDetected {len(constant_cols)} constant columns:')
    print(constant_cols)
else:
    print('\nNo constant columns detected.')

"""## Supervised Learning: Classification

### 1. Prepare Data for Modeling (Train-Test Split)
"""

# Ensure 'Domestic' is numerical (0/1) in X
if 'Domestic' in X.columns and X['Domestic'].dtype == 'bool':
    X['Domestic'] = X['Domestic'].astype(int)

# Convert target variable 'y' to numerical (0 for False, 1 for True)
y_numeric = y.astype(int)

print("Target variable 'y' converted to numerical (0/1).")
print(f"X shape: {X.shape}, y_numeric shape: {y_numeric.shape}")

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
# Using a 80/20 split, stratify by y to ensure similar class distribution in both sets
X_train, X_test, y_train, y_test = train_test_split(X, y_numeric, test_size=0.2, random_state=42, stratify=y_numeric)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

print("Data split into training and testing sets.")

"""### 2. Model Implementation and Evaluation

### 2.1 Logistic Regression
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Initialize Logistic Regression model
# Due to the large dataset, using 'lbfgs' solver might be slow or memory intensive. 'saga' or 'liblinear' are often better.
# max_iter is increased to ensure convergence, class_weight='balanced' to handle potential class imbalance.
# Fitting a model on the full 6.8 million rows might be too computationally expensive or memory-intensive for Colab free tier.
# Let's consider training on a sample first, or a model that scales better.

# For initial exploration, let's use a smaller sample of the training data if it's too large
sample_size_lr = min(100000, len(X_train)) # Use 100k samples or the full X_train if smaller

if sample_size_lr < len(X_train):
    print(f"Training Logistic Regression on a sample of {sample_size_lr} rows from X_train due to dataset size.")
    X_train_sampled_lr = X_train.sample(n=sample_size_lr, random_state=42)
    y_train_sampled_lr = y_train.loc[X_train_sampled_lr.index]
else:
    X_train_sampled_lr = X_train
    y_train_sampled_lr = y_train

# Instantiate and train the model
log_reg = LogisticRegression(solver='liblinear', random_state=42, n_jobs=-1, class_weight='balanced', max_iter=200)
print("Training Logistic Regression model...")
log_reg.fit(X_train_sampled_lr, y_train_sampled_lr)
print("Logistic Regression model trained.")

# Make predictions
y_pred_lr = log_reg.predict(X_test)

# Evaluate the model
print("\n--- Logistic Regression Evaluation ---")
print(f"Accuracy: {accuracy_score(y_test, y_pred_lr):.4f}")
print(f"Precision: {precision_score(y_test, y_pred_lr):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_lr):.4f}")
print(f"F1-score: {f1_score(y_test, y_pred_lr):.4f}")

# Confusion Matrix
cm_lr = confusion_matrix(y_test, y_pred_lr)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_lr, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix - Logistic Regression')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""### 2.2 Decision Tree Classifier"""

from sklearn.tree import DecisionTreeClassifier

# Initialize Decision Tree Classifier model
# Set random_state for reproducibility
# class_weight='balanced' to handle potential class imbalance
# For initial exploration, let's use a smaller sample of the training data if it's too large
sample_size_dt = min(100000, len(X_train)) # Use 100k samples or the full X_train if smaller

if sample_size_dt < len(X_train):
    print(f"Training Decision Tree Classifier on a sample of {sample_size_dt} rows from X_train due to dataset size.")
    X_train_sampled_dt = X_train.sample(n=sample_size_dt, random_state=42)
    y_train_sampled_dt = y_train.loc[X_train_sampled_dt.index]
else:
    X_train_sampled_dt = X_train
    y_train_sampled_dt = y_train

dt_classifier = DecisionTreeClassifier(random_state=42, class_weight='balanced')
print("Training Decision Tree Classifier model...")
dt_classifier.fit(X_train_sampled_dt, y_train_sampled_dt)
print("Decision Tree Classifier model trained.")

# Make predictions
y_pred_dt = dt_classifier.predict(X_test)

# Evaluate the model
print("\n--- Decision Tree Classifier Evaluation ---")
print(f"Accuracy: {accuracy_score(y_test, y_pred_dt):.4f}")
print(f"Precision: {precision_score(y_test, y_pred_dt):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_dt):.4f}")
print(f"F1-score: {f1_score(y_test, y_pred_dt):.4f}")

# Confusion Matrix
cm_dt = confusion_matrix(y_test, y_pred_dt)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_dt, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix - Decision Tree Classifier')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""### 2.3 Random Forest Classifier"""

from sklearn.ensemble import RandomForestClassifier

# Initialize Random Forest Classifier model
# Set random_state for reproducibility
# class_weight='balanced' to handle potential class imbalance
# For initial exploration, let's use a smaller sample of the training data due to its complexity and memory footprint
sample_size_rf = min(100000, len(X_train)) # Use 100k samples or the full X_train if smaller

if sample_size_rf < len(X_train):
    print(f"Training Random Forest Classifier on a sample of {sample_size_rf} rows from X_train due to dataset size.")
    X_train_sampled_rf = X_train.sample(n=sample_size_rf, random_state=42)
    y_train_sampled_rf = y_train.loc[X_train_sampled_rf.index]
else:
    X_train_sampled_rf = X_train
    y_train_sampled_rf = y_train

# Using a smaller number of estimators for initial pass to save time and memory
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1, class_weight='balanced')
print("Training Random Forest Classifier model...")
rf_classifier.fit(X_train_sampled_rf, y_train_sampled_rf)
print("Random Forest Classifier model trained.")

# Make predictions
y_pred_rf = rf_classifier.predict(X_test)

# Evaluate the model
print("\n--- Random Forest Classifier Evaluation ---")
print(f"Accuracy: {accuracy_score(y_test, y_pred_rf):.4f}")
print(f"Precision: {precision_score(y_test, y_pred_rf):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_rf):.4f}")
print(f"F1-score: {f1_score(y_test, y_pred_rf):.4f}")

# Confusion Matrix
cm_rf = confusion_matrix(y_test, y_pred_rf)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix - Random Forest Classifier')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()